# Generated by Django 5.1.3 on 2025-01-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='message_id',
            field=models.CharField(max_length=255),
        ),
    ]
