# Generated by Django 5.1.3 on 2025-01-31 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_gateway', '0002_alter_whatsappmessage_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappuser',
            name='phone_number_id',
        ),
        migrations.AlterField(
            model_name='whatsappuser',
            name='wa_id',
            field=models.CharField(max_length=255),
        ),
    ]
